### ISSUE TITLE
Smile audit not working

### ISSUE THREAD

**Issue by jl2035** [Smile-SA/odoo_addons#18]
I created two rules like this:

```
 id | create_uid | log_unlink | values_id |        create_date         |  name   | log_write | write_uid | state |         write_date         | active | model_id | log_create | action_id 
----+------------+------------+-----------+----------------------------+---------+-----------+-----------+-------+----------------------------+--------+----------+------------+-----------
  2 |          1 | t          |        11 | 2016-07-28 08:54:45.579812 | Userlog | t         |         1 | done  | 2016-07-28 08:54:51.632319 | t      |       91 | t          |        82
  1 |          1 | t          |           | 2016-07-28 08:46:02.418244 | User    | t         |         1 | done  | 2016-07-28 08:54:56.290982 | t      |       92 | t          |          
```

but I don't get any logs.

Is it possible that I totally missunderstood what this module is about?

**Comment by smile-odoo-gu** [comment]
Hello,

I suggest you to :
1. create a audit rule on Partner
2. modify a contact
3. click on "View audit logs" into the Action menu of the modified contact

It's ok for you ?

Have a nice day,
Corentin

**Comment by corentinpb** [comment]
Hello,

I suggest you to :
1. create a audit rule on Partner
2. modify a contact
3. click on "View audit logs" into the Action menu of the modified contact

It's ok for you ?

Have a nice day,
Corentin

**Comment by jl2035** [comment]
oh.. that works yes. i thought that i could log user logins with this module, but looks like that doesn't work.

@corentinpb thanks for your help
