### ISSUE TITLE
[smile_redis_session_store] Odoo 10 configuration failure

### ISSUE THREAD

**Issue by vodwood** [Smile-SA/odoo_addons#33]
I have installed the plugin (no errors thrown during the installation). These are the lines appended to the odoo config as per the readme:

enable_redis = True
redis_host = somehost.87ghsl.0001.euc1.cache.amazonaws.com
redis_port = 6379

Resulting behaviour - website cannot load. Nothing is observed in the log. 
Can you please advise where to debug further?

(not an issue of AWS, everything is configured correctly on that end)

**Comment by isabellerichard** [comment]
Hi,

Did you install package `python-redis` on the server hosting Odoo, via `apt-get install python-redis` ?

If you try to configure a Redis server (only for test) on the server hosting Odoo, via `apt-get install redis-server`, and use default options, does it work ?
https://github.com/Smile-SA/odoo_addons/tree/10.0/smile_redis_session_store#usage

**Comment by vodwood** [comment]
Hi Isabelle,

Thank you. After configuring Redis locally I've verified that the plugin is working.

I apologize, I screwed up the security group setup on amazon, so the connection was timing out - my fault. Sorry for the issue. Please feel free to close as irrelevant. 

Thank you for the plugin!

**Comment by isabellerichard** [comment]
You're welcome :)
