### ISSUE TITLE
[11.0] Turn on INIT flag make noupdate does not work

### ISSUE THREAD

**Issue by xubiuit** [Smile-SA/odoo_addons#51]
Hi guys,
Please help me to review and explain the purpose of this line:
https://github.com/Smile-SA/odoo_addons/blob/6d41921ba2e054c078b4e621f8f1fcc11b5da172/smile_upgrade/models/registry.py#L43

As my understanding that: You are turning on the init mode which make flag noupdate of native Odoo does not work properly. When a module was marked as init that means: hey odoo, install new module then Odoo does not check noupdate on XML data.

Thanks,
Binh Nguyen

**Comment by madecsmile** [comment]
Hi
Thanks you, this is corrected here 9bec41034e07e2e0860fd146e851a2849d08022e
Applied on v11, v12, v13.

Martin

**Comment by xubiuit** [comment]
Thanks Martin. We can close this ticket here
