### ISSUE TITLE
"'ir.cron' object has no attribute '_setup_base'" 

### ISSUE THREAD

**Issue by yk2kus** [Smile-SA/odoo_addons#6]
Version 8.0
Error on installation

ParseError: "'ir.cron' object has no attribute '_setup_base'" while parsing /home/yoges/workspace/OpenERP80/module-apps/smile_checklist/demo/checklist_demo.xml:5, near
<record model="checklist" id="cron_checklist">
      <field name="name">Cron checklist</field>
      <field name="action_id" eval="False"/>
      <field name="act_window_ids" eval="False"/>
      <field name="model_id" ref="base.model_ir_cron"/>
      <field name="active" eval="True"/>
      <field name="view_ids" eval="False"/>
    </record>

**Comment by isabellerichard** [comment]
Hi,

I installed the last version of smile_checklist on a database with demo data, with the last version of Odoo 8.0. I didn't reproduce your error.

Do you use the last version of Odoo 8.0 ?

**Comment by yk2kus** [comment]
I checked on Version 8.0-c7d8e97, will check on latest version and report back.

**Comment by isabellerichard** [comment]
Your version was commited in November, but the method _setup_base was only added in January (as you can see in this commit: https://github.com/odoo/odoo/commit/5fee95ca6366954839e6db0cec5cf1b9b06c023d).

Please tell me if upgrading your server is ok for you then I will close this issue :)

**Comment by yk2kus** [comment]
yes thanks it got installed with latest version. however it doesn't allow me to save a task because field is required not auto filled and not visible on the view.

**Comment by isabellerichard** [comment]
I fixed the issue of the task creation.

**Comment by yk2kus** [comment]
thanks a lot.
