### ISSUE TITLE
smile_account_asset missing field [12 CE]

### ISSUE THREAD

**Issue by luchovr** [Smile-SA/odoo_addons#61]
Hi.....
When try to install the module smile_account_asset, gives me an error, and tells me (log file) that I should add the field "**parent_path = fields. Char(index=True)**"
I add to account_asset_asset.py and it allows me to install without problem.
Is that correct?
Thank you!

**Comment by smile-odoo-gu** [comment]
Yes, we will fix it, thanks for report. Isabelle

**Comment by isabellerichard** [comment]
Yes, we will fix it, thanks for report. Isabelle
