### ISSUE TITLE
[13] smile_access_control: duplicate user profile

### ISSUE THREAD

**Issue by matthieujoossen** [Smile-SA/odoo_addons#69]
Environment:
- Odoo 13.0 (Community Edition) commit 054d4bc6bc219bcc6b0a64265e8d7e9c7423dbc8
- Smile Addons 13.0 commit 4f0d0d4dd346a55c8065e2cf07387d6777a5fc86

When I duplicate user profile, new user is duplicated as user with `user_profile_id` set with original user profile's ID.

Is this the expected behavior?

**Comment by isabellerichard** [comment]
Hi Matthieu,

This rules exist since version 9.0 of the module :
> When I duplicate a user profile, I create a user linked to this profile.

Is this annoying for your usage?

**Comment by matthieujoossen** [comment]
Hi Isabelle,

> Is this annoying for your usage?

No. I don't do this every day.
I just find that it is not necessarily intuitive. Another action "Create user from profile" would seem more logical to me.
