### ISSUE TITLE
[13.0] Community smile_web_impex issue on aplication kanban view

### ISSUE THREAD

**Issue by sergioeix** [Smile-SA/odoo_addons#97]
As far as i test this traceback only happens on applications app in kanban view, stock app and invoicing/accounting app

![image](https://user-images.githubusercontent.com/62206774/100464268-96b7f800-30cd-11eb-9bb5-c45c0405a02c.png)

PD Great feature :)
B/R

**Comment by isabellerichard** [comment]
Hi, sorry for the delay, we applied a fix on smile_web_impex on version 13.0.  
Regards!
